import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import ThemeSwitchIcon from "@/components/ThemeSwitchIcon";
import ThemeTransition from "@/components/ThemeTransition";
import { LanguageProvider } from "@/components/contexts/LanguageContext";
import LanguageSwitch from "@/components/LanguageSwitch";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <LanguageProvider>
            <div className="fixed top-4 right-4 z-50 flex items-center gap-2">
              <LanguageSwitch />
              <ThemeSwitchIcon />
            </div>
            <ThemeTransition>
              {children}
            </ThemeTransition>
          </LanguageProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
